
spring:
  profiles: user
  application:
    name: microservice-b-user-server  # 这也是注册在注册中心使用的名字
server:
  port: 8001

eureka:
  instance:
    hostname: user1 # Eureka服务端的实例名称
  client:
    register-with-eureka: true # false表示不向注册中心注册自己
    fetchRegistry: true  #取回注册信息
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/, http://peer2:7002/eureka/, http://peer3:7003/eureka/
