
spring:
  profiles: peer1
  application:
    name: microservice-discovery-eureka1
server:
  port: 7001

eureka:
  instance:
    hostname: peer1 # Eureka服务端的实例名称
  client:
    register-with-eureka: true # false表示不向注册中心注册自己
    fetchRegistry: true  #取回注册信息
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/, http://peer2:7002/eureka/, http://peer3:7003/eureka/
    
---

spring:
  profiles: peer2
  application:
    name: microservice-discovery-eureka2
server:
  port: 7002

eureka:
  instance:
    hostname: peer1 # Eureka服务端的实例名称
  client:
    register-with-eureka: true # false表示不向注册中心注册自己
    fetchRegistry: true  #取回注册信息
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/

---

spring:
  profiles: peer3
  application:
    name: microservice-discovery-eureka3
server:
  port: 7003

eureka:
  instance:
    hostname: peer3 # Eureka服务端的实例名称
  client:
    register-with-eureka: true # false表示不向注册中心注册自己
    fetchRegistry: true  #取回注册信息
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/